import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author family
 */
public class RotorSent extends javax.swing.JFrame {
Connection con;
 PreparedStatement ps;
 PreparedStatement ps1;
 PreparedStatement ps2;
 ResultSet rs;
 String F_ID;
  ResultSet rs1;
  ResultSet rs2;
  
    /**
     * Creates new form RotorSent
     */
    public RotorSent() {
        initComponents();
        FillCombo();
    }
    
private void FillCombo(){
        try{
              Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
    String url = "jdbc:ucanaccess://C:\\Users\\AmandeepKaur\\Desktop\\g\\PrateekIndustries.accdb";
             con = DriverManager.getConnection(url);
             ps = con.prepareStatement("select * from Firm");
             rs = ps.executeQuery();
        while(rs.next()){
            String name = rs.getString("Firm_Name");
            jComboBox1.addItem(name);
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prateek Industries - Supply Of Rotor");

        jLabel1.setText("Name Of Firm");

        jLabel2.setText("Stamping");

        jLabel3.setText("Size");

        jLabel4.setText("Date Of Rotor Sent");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(80, 80, 80)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(42, 42, 42)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(50, 50, 50)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(95, 95, 95))))
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    try {
       if(jComboBox2.getItemCount()>0)
                {
                jComboBox2.removeAllItems();
                 }
                 String name1 = (String) jComboBox1.getSelectedItem();
                   ps = con.prepareStatement("select Firm_ID from Firm where Firm_Name = '" + name1 +"'");
                     rs1 = ps.executeQuery();
                while(rs1.next()){
                    F_ID = rs1.getString("Firm_ID");  
        }   
                 ps = con.prepareStatement("select * from Orders where Firm_ID = '" + F_ID +"'");
                     rs1 = ps.executeQuery();
                                 while(rs1.next()){
                String stamp =  rs1.getString("Stamping");
                jComboBox2.addItem(stamp);              
                                 } // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
    catch(Exception e)
    { 
    JOptionPane.showMessageDialog(this, e);
    }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String drms = null;
    String oid = null;
        try {
        String stamp1 = (String) jComboBox2.getSelectedItem();
        String size1 = (String) jComboBox3.getSelectedItem();
                   ps = con.prepareStatement("select * from Orders where Firm_ID = '" + F_ID +"' AND Stamping = '" + stamp1 + "' AND Size = '" + size1 +"'");
                     rs1 = ps.executeQuery();
                     while(rs1.next()){
                 oid =  rs1.getString("Order_ID");
                 drms =  rs1.getString("Date_Of_Raw_Material_Supply");
                 }
                     JOptionPane.showMessageDialog(this, oid + "   " + drms);
        Timestamp dateformat = new Timestamp((jDateChooser1.getDate()).getTime());
             ps = con.prepareStatement("UPDATE Orders SET Date_OF_Rotor_Sent = '"+ dateformat +"' WHERE Firm_ID = '" + F_ID + "' AND Stamping = '" + stamp1 + "' AND Size = '" + size1 +"'");
         ps.execute();// TODO add your handling code here:
    } catch (SQLException ex) {
        Logger.getLogger(RotorSent.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
  try {

            // ps = con.prepareStatement("select * from Firm where Firm_Name = '"  + name +" '" );
            //ResultSet F_ID = ps.executeQuery();
            if(jComboBox3.getItemCount()>0)
            jComboBox3.removeAllItems();

            if(jComboBox2.getSelectedItem()!=null) {
                String stamp = jComboBox2.getSelectedItem().toString();
                ps = con.prepareStatement("select Size from Orders where Firm_ID = '"  + F_ID +" ' AND Stamping = '" + stamp + "'" );
                rs2 = ps.executeQuery();
                // String[] stamp = new String[5];
                while(rs2.next())
                {
                    jComboBox3.addItem(rs2.getString("Size"));
                }
            }// TODO add your handling code here:
    } catch (SQLException ex) {
        Logger.getLogger(RotorSent.class.getName()).log(Level.SEVERE, null, ex);
    }//GEN-LAST:event_jComboBox2ActionPerformed
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RotorSent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RotorSent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RotorSent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RotorSent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RotorSent().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
